# Site settings
title:          Achal Dave
description:    "Home"
url:            "https://achaldave.space"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Achal Dave
  url:          https://achaldave.space
  email:        achaldave28@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         achaldave
